config/routes.rb
Valentine::Application.routes.draw do

  resources :photos

  resources :charges

  post "search" => "users#index", :as => "search"
  get "matches" => "users#match", :as => "match"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"
  get "signup" => "users#new", :as => "signup"
  get "get_picture/:id/:index" => 'users#find_picture'

  resources :users

  root :to => 'users#new'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :message, :receiver_email, :user_id

  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :user_id, :name, :picture, :is_profile

  belongs_to :user

  mount_uploader :picture, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  authenticates_with_sorcery!

  attr_accessible :about_me, :age, :email, :first_name, :gender, :location, :password, :password_confirmation, :stripe_id

  has_many :photos
  has_many :messages

  validates :email, :uniqueness => true
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password

  searchable do
    text :about_me, :first_name, :location, :age
  end

def customer_emails
  customer_emails = []
  Stripe::Customer.all.data.each do |c|
    customer_emails << c.email
  end
  customer_emails
end

def is_paid
  customer_emails.include?(self.email)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_users_list
    current_users.map {|u| u.first_name}
  end

  helper_method :current_users_list

  def current_user_id_list
    current_users.map {|u| u.id}
  end

  helper_method :current_user_id_list

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    user = user.find(params[:user_id])

    customer = Stripe::Customer.create(
      :email => user.email,
      :card  => params[:stripeToken],
      :plan => "paid"
    )

    user.stripe_id = customer.stripe_id
    user.save

    binding.pry

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(params[:photo])
    @photo.user_id = current_user.id
    if @photo.save
      redirect_to user_url(current_user.id)
    else
      redirect_to user_url(current_user.id), notice: "Oops. Photo wouldn't upload. Try again :)"
    end
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    user = login(params[:email], params[:password])
    if user
      redirect_back_or_to user_url(user.id), :notice => "You're logged in:)"
    else
      flash.now.alert = "Invalid email or password. Try again!"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :except => [:create, :new]

  def index
    if current_user
      if current_user.gender == ("M" || "m")
        gender = "F" || "f"
      else
        gender = "M" || "m"
      end
    end
    query = params[:query]
    if query.blank?
      @users = User.where(:gender => gender)
    else
      search = User.search { fulltext query }
      @users = search.results
    end
  end

  def find_picture
    user = User.find(params[:id])
    index = params[:index]
    index = index.to_i
    render json: user.photos[index].picture
  end

  def show
    @user = User.find(params[:id])
    @photo = Photo.new
  end

  def create

    @user = User.new(params[:user])

    if @user.save
      auto_login(@user)
      if params[:stripeToken] != nil
          customer = Stripe::Customer.create(
            :email => @user.email,
            :card  => params[:stripeToken],
            :plan => "paid"
          )
      end
      redirect_to user_url(@user)
    else
      render :new
    end

  end

  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        @user.photos.each do |photo|
          photo.update_attributes(:is_profile => false)
        end
        @user.photos.find(params[:photo_id]).update_attributes(:is_profile => true)
        format.html { redirect_to @user, notice: 'Just saved your new profile :)' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
  end

  def match

  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<p>Find me in app/views/charges/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Valentine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <% if current_user %>
      Logged in as <%=link_to current_user.email, user_url(current_user.id) %>
      <%= link_to "Log Out", logout_url %>
    <% else %>
      <%= link_to "Sign up", signup_url %> |
      <%= link_to "Log In", login_url %>
    <% end %>
  </nav>

<%= yield %>

</body>
</html>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>

app/views/users/_add_photos.html.erb
<%= form_for(@photo, :html_options => {:multipart => true}) do |f| %>
  <%= f.label "Caption:" %>
  <%= f.text_field :name %>

  <%= f.file_field :picture %>
  <%= f.submit "Add this photo of your HOT self." %>
<% end %>

app/views/users/_free.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label "Email (this will be your username):" %> <br/>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :about_me %><br />
    <%= f.text_area :about_me %>
  </div>

  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up!" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :about_me %><br />
    <%= f.text_area :about_me %>
  </div>

  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div id = "user-pics">
    <% @user.photos.each do |photo| %>
      <div class = "user-pic">
        <input type="checkbox" name="photo_id" value="<%= photo.id %>">Make Profile<br>
        <%= image_tag photo.picture %><br>
      </div>
    <% end %>
  </div>


  <div class="actions">
    <%= f.submit "Save" %>
  </div>

<% end %>

app/views/users/index.html.erb
<%= form_tag search_url, :method => "post" do %>
  <%= label_tag "Search Users:" %>
  <%= text_field_tag "query" %>
  <%= submit_tag %>
<% end %>


<% @users.each do |user| %>

<ul>
  <li><%= link_to user.first_name, user_url(user.id) %></li>
  <li><%= user.about_me %></li>
  <li><%= user.gender %>, <%= user.age %> years old.</li>
  <li>From: <%= user.location %></li>
</ul>

<% end %>

app/views/users/match.html.erb
<%= current_user.first_name %>'s Matches:

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign Up</h1>


<p> Paid users can real-time message potential valentines, as well as view other singles with similar interests! </p>

<div class = "paid_form">
  <h3> As A Paid User </h3>

  <%= form_for(@user) do |f| %>

    <div class="field">
      <%= f.label "Email (this will be your username):" %> <br/>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :about_me %><br />
      <%= f.text_area :about_me %>
    </div>

    <div class="field">
      <%= f.label :age %><br />
      <%= f.number_field :age %>
    </div>

    <div class="field">
      <%= f.label "Gender (M or F)" %><br />
      <%= f.text_field :gender %>
    </div>

    <div class="field">
      <%= f.label "Location (city, state)" %><br />
      <%= f.text_field :location %>
    </div>

    <div class="field">
      <%= f.label :stripe_id %><br />
      <%= f.hidden_field :stripe_id, :value => "paid" %>
    </div>

    </br>
    <%= form_tag charges_path do %>

      <article>
        <label class="amount">
          <span>Paid Subscription: $5.00/month</span>
        </label>
      </article>

      <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key]%>"
        data-description="Paid Subscription">
      </script>

    <% end %>

    <div class="actions">
      <%= f.submit "Sign Up!" %>
    </div>

  <% end %>

</div>

<button type="button" id = "free_user_button">As A Free User</button>

<div id = "free_form">

</div>

<script>
  $("#free_user_button").on('click', function() {
    $("#free_form").empty().append("<%= j render :partial => 'free' %>");
  });
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.first_name%></h1>

<% if !@user.photos.empty? && !@user.photos.where(:is_profile => true).empty? %>
  <%= image_tag @user.photos.where(:is_profile => true)[0].picture %>
<% end %>

<ul>
  <li><%= @user.about_me %></li>
  <li><%= @user.gender %>, <%= current_user.age %> years old.</li>
  <li>From: <%= @user.location %></li>
</ul>

<% if @user == current_user && current_user.is_paid %>
  <%= link_to "Match Me!", match_url %>
<% end %>


<div id = "photos" >
  Photos of <%= @user.first_name %>:
  <% @user.photos.each_with_index do |photo, index| %>
    <p class = "photo-index" data = "<%= index %>">
      <%= index %>
    </p>
  <% end %>
  </br>
  <button id = "play-photos">Play Photos </button>
</div>

<div id = "shown-picture-div"> </div>
<img id = "shown-picture" src = "">


<% if @user == current_user %>
  <%= link_to "Edit Profile", edit_user_url(current_user.id) %>
  <% if @user.photos.length < 4 %>

    <div id = "post-photos"> Post some photos of yourself so everyone can see how hot you are! </div>
    <%= form_for(@photo, :html_options => {:multipart => true}) do |f| %>
      <%= f.label "Caption:" %>
      <%= f.text_field :name %>

      <%= f.file_field :picture %>
      <%= f.submit "Add this photo of your HOT self." %>

    <% end %>
  <% end %>
<% end %>

</br>
</br>

<% if current_user.is_paid %>
  When you click a name, past convo pops up, and can real-time message.
  </br>
  Currently online:
  </br>

  <% current_users_list.each_with_index do |first_name, index| %>
    <div class = "current-user-name">
      <%= first_name %>
      <span class = "name-index"> <%= index %> </span>
    </div>
  <% end %>

<% end %>


<div id = "hidden_id_list">
  <%= current_user_id_list %>
</div>

<input id = "hidden_user_id" type= "hidden" value = "<%= @user.id %>">

<div id = "hidden_photo_list">
  <% @user.photos.each do |photo| %>
    <img class = "hidden_user_photo" src= "<%= photo.picture %>">
  <% end %>
</div>


<%= link_to "All Valentines", users_url %>